name: show_time

on: push

jobs:
  job1:
    name: First job
    runs-on: ubuntu-latest
    steps:
    - name: Step one
      uses: actions/checkout@v2
    - name: Step two
      run: date
  job2:
    name: Second job
    runs-on: windows-latest
    steps:
    - name: Step one
      uses: actions/checkout@v2
    - name: Step two
      run: "Get-Date"
  job3:
    name: Third job
    runs-on: ubuntu-latest
    needs: [job1, job2]
    steps:
    - name: Show notification
      uses: actions/checkout@v2
      run: echo "Job1 and Job2 completed successfully"
      run: date
 